# Generated by Django 5.2.4 on 2025-07-24 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgc_code', models.CharField(help_text='9-digit PSGC code (e.g., 010000000 for Region I)', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'PSGC code must be a 9-digit number.')])),
                ('name', models.CharField(help_text='Region name (e.g., Region I - Ilocos Region)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
