# Generated by Django 5.2.4 on 2025-07-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sc_app', '0003_designation_group_office_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
