# Generated by Django 5.2.4 on 2025-07-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc_app', '0004_alter_personnel_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterModelOptions(
            name='disability',
            options={'ordering': ['code'], 'verbose_name_plural': 'Disabilities'},
        ),
        migrations.AlterModelOptions(
            name='eligibility',
            options={'verbose_name_plural': 'Eligibilities'},
        ),
        migrations.AlterModelOptions(
            name='ethnicity',
            options={'ordering': ['code'], 'verbose_name_plural': 'Ethnicities'},
        ),
    ]
