from django.contrib import admin
from .models import AccountableForm, Barangay, BenefitDisbursement, BenefitType, CityMunicipality, DeathDetail, Designation, Disability, Education, Eligibility, EmergencyContact, Ethnicity, Inventory, Issuance, MilestoneBenefit, MissedPayout, Office, Personnel, Province, Region, Relationship, Religion, SeniorCitizen, Signatory, TransferDetail

# Register your models here.
admin.site.register(AccountableForm)
admin.site.register(Barangay)
admin.site.register(BenefitDisbursement)
admin.site.register(BenefitType)
admin.site.register(CityMunicipality)
admin.site.register(DeathDetail)
admin.site.register(Designation)
admin.site.register(Disability)
admin.site.register(Education)
admin.site.register(Eligibility)
admin.site.register(EmergencyContact)
admin.site.register(Ethnicity)
admin.site.register(Inventory)
admin.site.register(Issuance)
admin.site.register(MilestoneBenefit)
admin.site.register(MissedPayout)
admin.site.register(Office)
admin.site.register(Personnel)
admin.site.register(Province)
admin.site.register(Region)
admin.site.register(Relationship)
admin.site.register(Religion)
admin.site.register(SeniorCitizen)
admin.site.register(Signatory)
admin.site.register(TransferDetail)